<?xml version="1.0" encoding="utf-8"?><Database Name="DA_DBMS" Class="DataConnDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-9E4M4BN\QUANGNHAT;Initial Catalog=DA_DBMS;Integrated Security=True" SettingsObjectName="DA_DBMS.Properties.Settings" SettingsPropertyName="DA_DBMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayCapNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Function Name="dbo.Logins" Method="Logins" IsComposable="true">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DangKyTK" Method="DangKyTK">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="matkhau" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="nhaplaimk" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="sdt" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="sex" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ngaysinh" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateMK" Method="UpdateMK">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="matkhaucu" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="matkhaumoi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="nhaplaimk" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DoiMK" Method="DoiMK" IsComposable="true">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="matkhaucu" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="matkhaumoi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="nhaplaimk" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Editprofile" Method="Editprofile">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="sex" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ava" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="ngaysinh" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemAnh" Method="ThemAnh">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="stream" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SelectAllKhachHang" Method="SelectAllKhachHang">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="SelectAllKhachHangResult">
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InfoSach" Method="InfoSach">
    <ElementType Name="InfoSachResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChitietSach" Method="ChitietSach">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <ElementType Name="ChitietSachResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayCapNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="MaNCC1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT_NCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaNXB1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TruSoChinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QuocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTacGia1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CongViec" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChuDe1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Sachtheochude" Method="Sachtheochude">
    <Parameter Name="chude" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SachtheochudeResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Tenchude" Method="Tenchude">
    <ElementType Name="TenchudeResult">
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Search_table" Method="Search_table" IsComposable="true">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="Search_tableResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Updatesoluong" Method="Updatesoluong">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getmakh" Method="getmakh" IsComposable="true">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemvaoCart" Method="ThemvaoCart">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GioHangtable" Method="GioHangtable" IsComposable="true">
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <ElementType Name="GioHangtableResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tongtien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Xoaspkhoicart" Method="Xoaspkhoicart">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Thongtindathang" Method="Thongtindathang">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ThongtindathangResult">
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getngaygiao" Method="getngaygiao" IsComposable="true">
    <Parameter Name="ngaydat" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.DateTime" />
  </Function>
  <Function Name="dbo.Tongtien" Method="Tongtien" IsComposable="true">
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.Taodonhang" Method="Taodonhang">
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <Parameter Name="phi" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="datedat" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="dategiao" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ResertGiohang" Method="ResertGiohang">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Tinhtrang" Method="Tinhtrang" IsComposable="true">
    <Parameter Name="tt" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.Xoa_DonHang" Method="Xoa_DonHang">
    <Parameter Name="madh" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.chitiet_donhang" Method="chitiet_donhang">
    <Parameter Name="madh" Type="System.Int32" DbType="Int" />
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <ElementType Name="chitiet_donhangResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Lichsuadonhang" Method="Lichsuadonhang">
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <ElementType Name="LichsuadonhangResult">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhiGiaoDich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrangDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TacGia_table" Method="TacGia_table">
    <ElementType Name="TacGia_tableResult">
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CongViec" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.checkTacGia" Method="checkTacGia" IsComposable="true">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemTG" Method="ThemTG">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="que" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="congviec" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="quoctich" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaysinh" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaTG" Method="SuaTG">
    <Parameter Name="matg" Type="System.Int32" DbType="Int" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="que" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="congviec" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="quoctich" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngaysinh" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaTG" Method="XoaTG">
    <Parameter Name="matg" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.checkNXB" Method="checkNXB" IsComposable="true">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaNXB" Method="XoaNXB">
    <Parameter Name="manxb" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemNXB" Method="ThemNXB">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="truso" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="quocgia" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="web" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SuaNXB" Method="SuaNXB">
    <Parameter Name="manxb" Type="System.Int32" DbType="Int" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="truso" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="quocgia" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="web" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NXB_table" Method="NXB_table">
    <ElementType Name="NXB_tableResult">
      <Column Name="MaNXB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TruSoChinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QuocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.checkNCC" Method="checkNCC" IsComposable="true">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NCCtable" Method="NCCtable">
    <ElementType Name="NCCtableResult">
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT_NCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SuaNCC" Method="SuaNCC">
    <Parameter Name="maNCC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="web" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemNCC" Method="ThemNCC">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="web" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaNCC" Method="XoaNCC">
    <Parameter Name="maNCC" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DonHangtable" Method="DonHangtable">
    <ElementType Name="DonHangtableResult">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhiGiaoDich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XacnhanDonhang" Method="XacnhanDonhang">
    <Parameter Name="madh" Type="System.Int32" DbType="Int" />
    <Parameter Name="tinhtrang" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getTenKH" Method="getTenKH" IsComposable="true">
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.CheckGiohang" Method="CheckGiohang" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Capquyen" Method="Capquyen">
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <Parameter Name="quyen" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KhachHangtable" Method="KhachHangtable">
    <ElementType Name="KhachHangtableResult">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Xoa_KH" Method="Xoa_KH">
    <Parameter Name="makh" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ConvertQuyen" Method="ConvertQuyen" IsComposable="true">
    <Parameter Name="quyen" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckSach" Method="CheckSach" IsComposable="true">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SachTable" Method="SachTable">
    <ElementType Name="SachTableResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayCapNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThemSach" Method="ThemSach">
    <Parameter Name="tensach" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="matacgia" Type="System.Int32" DbType="Int" />
    <Parameter Name="giaban" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="mota" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ngaycn" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Parameter Name="manxb" Type="System.Int32" DbType="Int" />
    <Parameter Name="mancc" Type="System.Int32" DbType="Int" />
    <Parameter Name="machude" Type="System.Int32" DbType="Int" />
    <Parameter Name="anh" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSach" Method="UpdateSach">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Parameter Name="giaban" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaSach" Method="XoaSach">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TenNCC" Method="TenNCC">
    <ElementType Name="TenNCCResult">
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TenNXB" Method="TenNXB">
    <ElementType Name="TenNXBResult">
      <Column Name="MaNXB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TenTacGia" Method="TenTacGia">
    <ElementType Name="TenTacGiaResult">
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.convert_mancc" Method="convert_mancc" IsComposable="true">
    <Parameter Name="tenncc" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.convert_manxb" Method="convert_manxb" IsComposable="true">
    <Parameter Name="tennxb" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.convert_matg" Method="convert_matg" IsComposable="true">
    <Parameter Name="tentg" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.convert_machude" Method="convert_machude" IsComposable="true">
    <Parameter Name="tenchude" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetQuyen" Method="GetQuyen" IsComposable="true">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckHethang" Method="CheckHethang" IsComposable="true">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ChitietSach" Method="ChitietSach1">
    <Parameter Name="masach" Type="System.Int32" DbType="Int" />
    <ElementType Name="ChitietSachResult1">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayCapNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="MaNCC1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT_NCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaNXB1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TruSoChinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QuocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaTacGia1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CongViec" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaChuDe1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConvertQuyen1" Method="ConvertQuyen1" IsComposable="true">
    <Parameter Name="quyen" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.DangKy" Method="DangKy" IsComposable="true">
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="matkhau" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="nhaplaimk" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Search_KH" Method="Search_KH">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="Search_KHResult">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Avatar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongkeBanchay" Method="ThongkeBanchay" IsComposable="true">
    <ElementType Name="ThongkeBanchayResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Decimal(29,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Thonghangcontrongkho" Method="Thonghangcontrongkho" IsComposable="true">
    <ElementType Name="ThonghangcontrongkhoResult">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>